openapi: 3.0.1
info:
  title: sinbad
  description: "This API documentation is for the sinbad project...."
  version: 1.0.0
tags: []
paths:
  /u/profile:
    get:
      summary: GetUserProfile
      deprecated: false
      description: Get full profile info. The user will be identified from the access token
      tags: []
      parameters:
        - name: Authorization
          in: header
          description: JWT Access Token obtained during the login/sign up
          required: false
          example: ''
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  first_name:
                    type: string
                    description: 'Customer first name '
                  last_name:
                    type: string
                    description: 'Customer last name '
                  mobile:
                    type: string
                    description: 'Customer mobile number '
                  email:
                    type: string
                    description: Customer email
                  address:
                    type: string
                    description: Customer Line 1 address
                  gender:
                    type: string
                    description: Customer gender
                required:
                  - first_name
                  - last_name
                  - mobile
                  - email
                  - address
                  - gender
          headers: {}
      security: []
    patch:
      summary: Update User Profile
      deprecated: false
      description: Get full profile info. The user will be identified from the access token
      tags: []
      parameters:
        - name: Authorization
          in: header
          description: JWT Access Token obtained during the login/sign up
          required: false
          example: ''
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  description: 'Customer first name '
                last_name:
                  type: string
                  description: 'Customer last name '
                mobile:
                  type: string
                  description: 'Customer mobile number '
                email:
                  type: string
                  description: Customer email
                address:
                  type: string
                  description: Customer Line 1 address
                gender:
                  type: string
                  description: Customer gender
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties: {}
          headers: {}
      security: []
  /t/rate:
    post:
      summary: Rate trip
      deprecated: false
      description: ''
      operationId: rateTrip
      tags: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TripRateInput'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
          headers: {}
        '422':
          description: Parameter Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
          headers: {}
      security: []
  /sv/nearby:
    get:
      summary: Get nearest Streetview image
      deprecated: false
      description: ''
      operationId: getNearestStreetViewImage
      tags: []
      parameters:
        - name: lat
          in: query
          description: ''
          required: true
          schema:
            type: number
            format: float64
        - name: lon
          in: query
          description: ''
          required: true
          schema:
            type: number
            format: float64
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NearestStreetViewImageResponse'
          headers: {}
      security: []
  /m/styles:
    get:
      summary: Map styles
      deprecated: false
      description: 'Contains map style urls '
      operationId: listMapStyles
      tags: []
      parameters:
        - name: Accept-Language
          in: header
          description: ''
          required: false
          example: ''
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MapStylesResponse'
              examples:
                '1':
                  summary: Success
                  value:
                    ok: true
                    data:
                      - name: default
                        style_url: https://styles.hudhud.sa/default.json
                        thumbnail_url: https://static.hudhud.sa/default_thumb.webp
          headers: {}
      security: []
  /u/session:
    post:
      summary: '[1] NewSession'
      deprecated: false
      description: >-
        First endpoint has to be called it's publicly exposed with no
        authentication. 

        This endpoint will create a new session record in the DB and it will
        retrun auth token for the subsequent api calles in order to not expose
        the rest of the endpoints publicly.


        The response will contain the session_auth_token which will be passed in
        the following calls in the header and the state in order for the client
        to route the user to right screen.
      tags: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email_or_mobile:
                  type: string
              required:
                - email_or_mobile
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewSessionResponse'
          headers: {}
      security: []
  /p/typeahead:
    get:
      summary: POIs typeahead search
      deprecated: false
      description: >-
        Search as you type feature, this endpoint searches POIs that have
        similar prefix and sends back the auto-completed matching results.
      operationId: getTypeahead
      tags: []
      parameters:
        - name: query
          in: query
          description: Prefix to search for
          required: true
          schema:
            type: string
        - name: lat
          in: query
          description: ''
          required: false
          schema:
            type: number
            format: double
        - name: lon
          in: query
          description: ''
          required: false
          schema:
            type: number
            format: double
        - name: Accept-Language
          in: header
          description: ''
          required: false
          example: ''
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PoisTypeaheadResponse'
              examples:
                '1':
                  summary: Success
                  value:
                    ok: true
                    data:
                      - id: e3_Bn48BNW7Fxf0YbFTq
                        address: >-
                          Mohisini Mall, Ash Shaikh Muhammad Ibn Mani Street,
                          Al-Awali, Makkah Al Mukarramah, Makkah Region, 24251,
                          Saudi Arabia
                        name: Daran Engineering Consultancy
                        category: engineering - consulting
                        coordinates:
                          lat: 39.891111
                          lon: 21.3625
                        ios_category_icon:
                          name: restaurant
                          color: blue
                        android_category_icon:
                          name: restaurant
                          color: blue
          headers: {}
      security: []
  /sv/{id}:
    get:
      summary: Get streetview image by id
      deprecated: false
      description: ''
      operationId: getStreetViewImage
      tags: []
      parameters:
        - name: id
          in: path
          description: ''
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StreetViewDetailResponse'
          headers: {}
        '400':
          description: Bad Request
          content:
            application/json:
              schema: &ref_0
                $ref: '#/components/schemas/ErrorResponse'
          headers: {}
        '404':
          description: Record Not Found
          content:
            application/json:
              schema: *ref_0
          headers: {}
      security: []
  /u/sessions/verify-otp:
    post:
      summary: '[2] VerifyOTP'
      deprecated: false
      description: >-
        This endpoint to verify the OTP with the session_auth_token in the
        header. It will return the UserSession which has the access token when
        the status is Active
      tags: []
      parameters:
        - name: Authorization
          in: header
          description: Pass the session auth token
          required: false
          example: ''
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                otp:
                  type: string
                  description: six digits OTP to verify
                  minLength: 6
                  maxLength: 6
                  pattern: ^[0-6]{6}$
              required:
                - otp
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifyOTPResponse'
          headers: {}
      security: []
  /p/{id}:
    get:
      summary: POI details
      deprecated: false
      description: ''
      operationId: getPoi
      tags: []
      parameters:
        - name: id
          in: path
          description: ''
          required: true
          schema:
            type: string
        - name: lat
          in: query
          description: ''
          required: false
          schema:
            type: number
            format: float64
        - name: lon
          in: query
          description: ''
          required: false
          schema:
            type: number
            format: float64
        - name: Accept-Language
          in: header
          description: ''
          required: false
          example: ''
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PoiDetailsResponse'
              examples:
                '1':
                  summary: Success
                  value:
                    ok: true
                    data:
                      id: pWoPoI8B8Xvus8TK_yvV
                      address: >-
                        Mohisini Mall, Ash Shaikh Muhammad Ibn Mani Street,
                        Al-Awali, Makkah Al Mukarramah, Makkah Region, 24251,
                        Saudi Arabia
                      name: Daran Engineering Consultancy
                      category: engineering - consulting
                      coordinates:
                        lat: 39.891111
                        lon: 21.3625
                      phone_number: '0533132053'
                      website: www.darna.com.sa
                      rating: 4.5
                      ratings_count: 706
                      instagram: https://www.instagram.com/darna.22/
                      description: >-
                        who are weDarna Engineering Consulting is a destination
                        for those seeking excellence by providing comprehensive
                        engineering consulting services in innovative ways and
                        highly qualified and experienced consultants in the
                        fields of infrastructure, designing and implementing
                        electrical, civil and architectural plans, striving to
                        create sustainable development in the field of
                        consulting and design in a way that preserves the
                        nobility of the past and the ambition of the future for
                        an ambitious nation, a prosperous economy and a society.
                        Vital contributors to achieving the Kingdom of Saudi
                        Arabia’s Vision 2030.Our messageWe are committed to
                        providing advisory and administrative services in
                        accordance with the highest international quality
                        standards, maintaining optimal exploitation of available
                        resources with trained and qualified national
                        competencies to achieve the satisfaction of our
                        customers and partners.Our visionThe summit is our
                        homerate usOriginality, innovation, ambition, fluency,
                        agility, flexibility, qualityOur goalsDistinctive and
                        attractive architectural designs, comprehensive project
                        supervision using innovative and economical methods,
                        project management with high technologies, and providing
                        service that exceeds the expectations of our customers
                        and partners.
                      distance: 7634621.835636893
                      duration: 31.457
                      is_open: true
                      opening_hours:
                        saturday:
                          - start: 600
                            end: 720
                          - start: 1000
                            end: 1600
                        sunday:
                          - start: 600
                            end: 720
                        monday:
                          - start: 600
                            end: 720
                          - start: 1000
                            end: 1600
                        tuesday:
                          - start: 600
                            end: 720
                        wednesday:
                          - start: 600
                            end: 720
                          - start: 1000
                            end: 1600
                        thursday:
                          - start: 600
                            end: 720
                        friday:
                          - start: 600
                            end: 720
                          - start: 1000
                            end: 1600
                      media_urls:
                        - type: image
                          url: https://media.hudhud.sa/4578.webp
          headers: {}
        '404':
          description: Record Not Found
          content:
            application/json:
              schema: *ref_0
              examples:
                '1':
                  summary: Success
                  value:
                    ok: false
                    message: the requested poi was not found
                    code: H04
          headers: {}
      security: []
  /u/sessions/resend-otp:
    post:
      summary: ResendOTP
      deprecated: false
      description: >-
        This endpoint can be called when the session state is in
        PENDING_FOR_OTP_VERIFICATION to resent OTP after passing the
        can_request_resend_otp timestamp.


        The response will contain the user session object which has the state in
        order for the client to route the user to right screen.
      tags: []
      parameters:
        - name: Authorization
          in: header
          description: Pass the session auth token
          required: false
          example: ''
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema: &ref_1
                $ref: '#/components/schemas/ResendOTPResponse'
          headers: {}
      security: []
  /sv/scene/{id}:
    get:
      summary: Get streetview scene by id
      deprecated: false
      description: ''
      operationId: getStreetViewScene
      tags: []
      parameters:
        - name: id
          in: path
          description: ''
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema: &ref_2
                $ref: '#/components/schemas/StreetViewSceneResponse'
          headers: {}
        '400':
          description: Bad Request
          content:
            application/json:
              schema: *ref_0
          headers: {}
        '404':
          description: Record Not Found
          content:
            application/json:
              schema: *ref_0
          headers: {}
      security: []
  /p:
    get:
      summary: List pois (pois search)
      deprecated: false
      description: ''
      operationId: listPois
      tags: []
      parameters:
        - name: page
          in: query
          description: ''
          required: false
          schema:
            type: integer
        - name: limit
          in: query
          description: ''
          required: false
          schema:
            type: integer
        - name: sort_by
          in: query
          description: ''
          required: false
          schema:
            type: string
            enum:
              - relevance
              - distance
            x-apidog:
              enumDescriptions:
                relevance: ''
                distance: ''
        - name: price_range
          in: query
          description: ''
          required: false
          schema:
            type: integer
            enum:
              - 1
              - 2
              - 3
              - 4
            x-apidog:
              enumDescriptions:
                '1': ''
                '2': ''
                '3': ''
                '4': ''
        - name: rating
          in: query
          description: ''
          required: false
          schema:
            type: number
            minimum: 0
            maximum: 5
            format: double
        - name: open_at
          in: query
          description: in UTC format
          required: false
          schema:
            type: string
            format: date-time
        - name: category
          in: query
          description: ''
          required: false
          schema:
            type: string
        - name: text
          in: query
          description: This should search the name,category and description ?
          required: false
          schema:
            type: string
        - name: next_page_token
          in: query
          description: When this is sent it takes precedence over page and limit.
          required: false
          schema:
            type: string
        - name: lat
          in: query
          description: ''
          required: false
          schema:
            type: number
            format: double
        - name: lon
          in: query
          description: ''
          required: false
          schema:
            type: number
            format: double
        - name: top_rated
          in: query
          description: ''
          required: false
          schema:
            type: boolean
        - name: Accept-Language
          in: header
          description: ''
          required: false
          example: ''
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PoisListResponse'
              examples:
                '1':
                  summary: Success
                  value:
                    ok: true
                    total: 100
                    next_page_token: somebase64encodedstring=
                    data:
                      - id: 4rtfdvb7rzw
                        name: Dunkin' donuts
                        rating: 2.1
                        ratings_count: 100
                        category: café
                        distance: 41.41
                        price_range: 2
                        accessibility: true
                        is_open: true
                        opening_hours:
                          saturday:
                            - opens_at: 600
                              closes_at: 720
                            - opens_at: 1000
                              closes_at: 1600
                          sunday:
                            - opens_at: 600
                              closes_at: 720
                          monday:
                            - opens_at: 600
                              closes_at: 720
                            - opens_at: 1000
                              closes_at: 1600
                          tuesday:
                            - opens_at: 600
                              closes_at: 720
                          wednesday:
                            - opens_at: 600
                              closes_at: 720
                            - opens_at: 1000
                              closes_at: 1600
                          thursday:
                            - opens_at: 600
                              closes_at: 720
                          friday:
                            - opens_at: 600
                              closes_at: 720
                            - opens_at: 1000
                              closes_at: 1600
                        phone_number: '+9664512'
                        coordinates:
                          lat: 39.891111
                          lon: 21.3625
                        website: https://hudhud.sa
                        instagram: ''
                        media_urls:
                          - type: picture
                            url: https://media.hudhud.sa/dsqdqs.jpeg
          headers: {}
      security: []
  /u/sessions:
    get:
      summary: GetSession
      deprecated: false
      description: >-
        This endpoint to retrive the user session info using the
        session_auth_token in the header in order for the client to refresh the
        state and reoute the client if necessary.
      tags: []
      parameters:
        - name: Authorization
          in: header
          description: Pass the session auth token
          required: false
          example: ''
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema: *ref_1
          headers: {}
      security: []
  /p/trending:
    get:
      summary: Trending POIs
      deprecated: false
      description: ''
      operationId: listTrendingPois
      tags: []
      parameters:
        - name: page
          in: query
          description: ''
          required: false
          schema:
            type: integer
        - name: limit
          in: query
          description: ''
          required: false
          schema:
            type: integer
        - name: next_page_token
          in: query
          description: ''
          required: false
          schema:
            type: string
        - name: lat
          in: query
          description: ''
          required: false
          schema:
            type: number
            format: double
        - name: lon
          in: query
          description: ''
          required: false
          schema:
            type: number
            format: double
        - name: Accept-Language
          in: header
          description: ''
          required: false
          example: ''
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PoisTrendingResponse'
              examples:
                '1':
                  summary: Success
                  value:
                    ok: true
                    next_page_token: somebase64encodedstring=
                    data:
                      - id: somedidsq
                        coordinates:
                          lat: 39.891111
                          lon: 21.3625
                        rating: 5
                        ratings_count: 100
                        name: َAlBaik
                        category: restaurant
                        trending_image_url: https://media.hudhud.sa/dqdv.webp
          headers: {}
      security: []
  /sv/scene/bbox:
    get:
      summary: Get streetview scences bbox
      deprecated: false
      description: ''
      operationId: getStreetViewSceneBBox
      tags: []
      parameters:
        - name: bbox
          in: query
          description: >-
            the format is <min_lon>,<min_lat>,<max_lon>,<max_lat> for example
            46.5424,24.5708,46.8534,24.8595
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema: *ref_2
          headers: {}
      security: []
components:
  schemas:
    GetUserProfileResponse:
      type: object
      properties:
        ok:
          type: boolean
        data:
          $ref: '#/components/schemas/UserProfile'
      required:
        - data
    UserSavedPOI:
      type: object
      properties:
        id:
          type: string
          description: 'unique identifier '
        user_id:
          type: string
          description: user
        poi: &ref_8
          $ref: '#/components/schemas/PoiDetails'
      required:
        - id
        - user_id
        - poi
    UserProfile:
      type: object
      properties:
        first_name:
          type: string
          description: 'Customer first name '
        last_name:
          type: string
          description: 'Customer last name '
        mobile:
          type: string
          description: 'Customer mobile number '
        email:
          type: string
          description: Customer email
        address:
          type: string
          description: Customer Line 1 address
        gender:
          type: string
          description: Customer gender
    VerifyOTPResponse:
      type: object
      properties:
        ok:
          type: boolean
        session: &ref_3
          $ref: '#/components/schemas/UserSession'
      required:
        - ok
        - session
    ResendOTPResponse:
      type: object
      properties:
        ok:
          type: boolean
        data: *ref_3
      required:
        - ok
        - data
    NewSessionResponse:
      type: object
      properties:
        ok:
          type: boolean
        data:
          type: object
          properties:
            session_auth_token:
              type: string
              description: JWT token for accessing subsequent session APIs
            state:
              type: string
              description: the state of the session
          required:
            - session_auth_token
            - state
      required:
        - ok
        - data
    Coordinates:
      type: object
      properties:
        lat:
          type: number
          format: double
        lon:
          type: number
          format: double
      required:
        - lat
        - lon
    UserSession:
      type: object
      properties:
        id:
          type: string
          description: Unique identifer for the user session
        email_or_mobile:
          type: string
          description: Either the email of mobile of the seesion
        state:
          type: string
          enum:
            - INIT
            - PENDING_FOR_OTP_VERIFICATION
            - OTP_VERIFIED
            - ACTIVE
        access_token:
          type: string
          description: JWT auth access token will be present only when the state is ACTIVE
        can_request_otp_resent_at:
          type: string
          format: date-time
          description: >-
            This will be present only when the state is
            PENDING_FOR_OTP_VERIFICATION. It is a UTC timestamp in RFC3339
            format to indicate the
        created_at:
          type: string
          format: date-time
          description: Timestamp for when the first session started
        updated_at:
          type: string
          format: date-time
          description: Timestamp for when the first session got updated
      required:
        - id
        - email_or_mobile
        - state
        - created_at
    UserSessionResponse:
      type: object
      properties:
        ok:
          type: boolean
        data: *ref_3
      required:
        - ok
        - data
    IosCategoryIcon:
      type: object
      properties:
        name:
          type: string
          description: name
        color:
          type: string
          enum:
            - systemGray
            - systemGray2
            - systemGray3
            - systemGray4
            - systemGray5
            - systemGray6
            - systemRed
            - systemGreen
            - systemBlue
            - systemOrange
            - systemYellow
            - systemPink
            - systemPurple
            - systemTeal
            - systemIndigo
            - systemBrown
            - systemMint
            - systemCyan
      required:
        - name
        - color
    AndroidCategoryIcon:
      type: object
      properties:
        name:
          type: string
        color:
          type: string
      required:
        - name
        - color
    StreetViewScene:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        next_id:
          type: integer
          nullable: true
        next_name:
          type: string
          nullable: true
        previous_id:
          type: integer
          nullable: true
        previous_name:
          type: string
          nullable: true
        west_id:
          type: integer
          nullable: true
        west_name:
          type: string
          nullable: true
        east_id:
          type: integer
          nullable: true
        east_name:
          type: string
          nullable: true
        geom:
          type: string
        point:
          type: object
          properties:
            lat:
              type: number
              format: float64
            lon:
              type: number
              format: float64
          required:
            - lat
            - lon
        created_at:
          type: string
        updated_at:
          type: string
      required:
        - point
        - created_at
        - updated_at
        - id
        - name
    StreetViewSceneResponse:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/StreetViewScene'
        ok:
          type: boolean
      required:
        - ok
        - data
    MapStyleItem:
      type: object
      properties:
        name:
          type: string
        style_url:
          type: string
        thumbnail_url:
          type: string
        type:
          type: string
          enum:
            - map_type
            - map_details
      required:
        - name
        - style_url
        - thumbnail_url
        - type
    MapStylesResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/MapStyleItem'
        ok:
          type: boolean
      required:
        - data
        - ok
    StreetViewImageDetails:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        metadata:
          type: string
        geom:
          type: string
        point:
          type: object
          properties:
            lat:
              type: number
              format: float64
            lon:
              type: number
              format: float64
          required:
            - lat
            - lon
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        url:
          type: string
      required:
        - id
        - name
        - point
        - created_at
        - updated_at
        - url
    StreetViewDetailResponse:
      type: object
      properties:
        ok:
          type: boolean
        data:
          $ref: '#/components/schemas/StreetViewImageDetails'
      required:
        - ok
        - data
    NearestStreetViewImageResponse:
      type: object
      properties:
        ok:
          type: boolean
        data:
          $ref: '#/components/schemas/StreetViewImageItem'
      required:
        - ok
    StreetViewImageItem:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        metadata:
          type: string
        geom:
          type: string
        point:
          type: object
          properties:
            lat:
              type: number
              format: float64
            lon:
              type: number
              format: float64
          required:
            - lat
            - lon
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        distance:
          type: number
          format: float64
        url:
          type: string
      required:
        - id
        - name
        - point
        - created_at
        - updated_at
        - distance
        - url
    SuccessResponse:
      type: object
      properties:
        ok:
          type: boolean
        data:
          type: object
          properties: {}
          nullable: true
      required:
        - ok
    ValidationError:
      type: object
      properties:
        ok:
          type: boolean
        message:
          type: object
          properties: {}
        code:
          type: string
      required:
        - ok
        - message
        - code
    TripRateInput:
      type: object
      properties:
        id:
          type: integer
          description: ID
        rating:
          type: integer
          enum:
            - 0
            - 1
            - 2
            - 3
            - 4
        trip_info:
          type: object
          properties: {}
        timestamp:
          type: integer
          format: uint64
      required:
        - id
        - rating
        - trip_info
        - timestamp
    OpeningHoursItem:
      type: object
      properties:
        start:
          type: integer
        end:
          type: integer
      required:
        - start
        - end
    ErrorResponse:
      type: object
      properties:
        ok:
          type: boolean
        message:
          type: string
        code:
          type: string
      required:
        - ok
        - message
        - code
    TrendingItem:
      type: object
      properties:
        id:
          type: string
        coordinates: &ref_5
          $ref: '#/components/schemas/Coordinates'
        rating:
          type: number
          format: double
        ratings_count:
          type: integer
        name:
          type: string
        category:
          type: string
        trending_image_url:
          type: string
        distance:
          type: number
          format: double
          description: in meters
      required:
        - id
        - coordinates
        - name
        - category
        - trending_image_url
    PoisListItem:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        rating:
          type: number
          format: double
          nullable: true
        ratings_count:
          type: integer
          nullable: true
        category:
          type: string
        distance:
          type: number
          format: double
          nullable: true
        price_range:
          type: integer
          enum:
            - 1
            - 2
            - 3
            - 4
          nullable: true
        accessibility:
          type: boolean
          nullable: true
        is_open:
          type: boolean
          nullable: true
        opening_hours:
          type: object
          properties:
            saturday:
              type: array
              items: &ref_4
                $ref: '#/components/schemas/OpeningHoursItem'
              nullable: true
            sunday:
              type: array
              items: *ref_4
              nullable: true
            monday:
              type: array
              items: *ref_4
              nullable: true
            tuesday:
              type: array
              items: *ref_4
              nullable: true
            wednesday:
              type: array
              items: *ref_4
              nullable: true
            thursday:
              type: array
              items: *ref_4
              nullable: true
            friday:
              type: array
              items: *ref_4
              nullable: true
          nullable: true
        phone_number:
          type: string
          nullable: true
        coordinates: *ref_5
        website:
          type: string
          nullable: true
        instagram:
          type: string
          nullable: true
        media_urls:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
              url:
                type: string
            required:
              - type
              - url
          nullable: true
      required:
        - id
        - name
        - category
        - coordinates
    PoiDetails:
      type: object
      properties:
        id:
          type: string
        address:
          type: string
        name:
          type: string
        category:
          type: string
        coordinates: *ref_5
        phone_number:
          type: string
          nullable: true
        website:
          type: string
          nullable: true
        rating:
          type: number
          format: double
          nullable: true
        ratings_count:
          type: integer
          nullable: true
        instagram:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        is_open:
          type: boolean
          nullable: true
        opening_hours:
          type: object
          properties:
            saturday:
              type: array
              items: *ref_4
              nullable: true
            sunday:
              type: array
              items: *ref_4
              nullable: true
            monday:
              type: array
              items: *ref_4
              nullable: true
            tuesday:
              type: array
              items: *ref_4
              nullable: true
            wednesday:
              type: array
              items: *ref_4
              nullable: true
            thursday:
              type: array
              items: *ref_4
              nullable: true
            friday:
              type: array
              items: *ref_4
              nullable: true
          nullable: true
        media_urls:
          type: array
          items:
            type: object
            properties:
              type:
                type: string
                enum:
                  - image
                  - video
              url:
                type: string
            required:
              - type
              - url
          nullable: true
        distance:
          type: number
          format: double
          description: distance in meters
          nullable: true
        duration:
          type: number
          format: double
          description: duration in seconds
          nullable: true
        android_category_icon: &ref_7
          $ref: '#/components/schemas/AndroidCategoryIcon'
        ios_category_icon: &ref_6
          $ref: '#/components/schemas/IosCategoryIcon'
      required:
        - id
        - address
        - name
        - category
        - coordinates
        - android_category_icon
        - ios_category_icon
    TypeaheadItem:
      type: object
      properties:
        type:
          type: string
          enum:
            - poi
            - category
        id:
          type: string
        address:
          type: string
        name:
          type: string
        category:
          type: string
        coordinates: *ref_5
        ios_category_icon: *ref_6
        android_category_icon: *ref_7
      required:
        - ios_category_icon
        - android_category_icon
        - name
        - type
    PoisTrendingResponse:
      type: object
      properties:
        ok:
          type: boolean
          description: >-
            Can be ignored by clients, errors should be checked using the status
            code following the http standard
        data:
          type: array
          items:
            $ref: '#/components/schemas/TrendingItem'
      required:
        - ok
        - data
    PoisListResponse:
      type: object
      properties:
        ok:
          type: boolean
          description: >-
            Can be ignored by clients, errors should be checked using the status
            code following the http standard
        total:
          type: integer
        next_page_token:
          type: string
        data:
          type: array
          items:
            $ref: '#/components/schemas/PoisListItem'
      required:
        - ok
        - total
        - data
    PoiDetailsResponse:
      type: object
      properties:
        ok:
          type: boolean
          description: >-
            Can be ignored by clients, errors should be checked using the status
            code following the http standard
        data: *ref_8
      required:
        - ok
        - data
    PoisTypeaheadResponse:
      type: object
      properties:
        ok:
          type: boolean
        data:
          type: array
          items:
            $ref: '#/components/schemas/TypeaheadItem'
      required:
        - ok
        - data
  securitySchemes: {}
servers:
  - url: https://api.dev.hudhud.sa
    description: Develop Env